name: Run R scripts

on:
  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ${{ matrix.config.os }}
    #container: ghcr.io/open-aims/seriatopora_analyses:main #put in the correct branch name
    container: ghcr.io/open-aims/${{ ${{ github.repository }} | tr [:upper:] [:lower:] }}:main #put in the correct branch name
    name: ${{ matrix.config.os }} 
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest}
    
    steps:
      - name: test
        run: |
          echo "${{ Github.repository }}"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4
      #  with:
      #   token: ${{ secrets.GITHUB_TOKEN }}

      #- name: Run Script
      #  run: |
      #    source("R/00_main.R")
      #  shell: Rscript {0}
